### ISSUE TITLE
Segfault with Server Push

### ISSUE THREAD

**Issue by dshafik** [bagder/curl#529]
OS: OS X Yosemite (10.10.5) & Ubuntu 15.10
Version: 7.45.0 (homebrew, and compiled from source on Ubuntu)

I am experiencing issues with server push. When I return `CURL_PUSH_DENY` I get a segfault, and with `CURL_PUSH_OK` I hit an assertion failure.

The code is a simplified version of the example code ([here](https://github.com/bagder/curl/blob/master/docs/examples/http2-serverpush.c)), however to simplify testing I just return `CURL_PUSH_OK` or `CURL_PUSH_DENY` as the entire callback body.

See https://gist.github.com/dshafik/ed98035e6cceed8abfe8#file-http2-serverpush-c-L160

With `CURL_PUSH_DENY` this is the segfault/bt on OS X:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000010000eb51 in Curl_http_done () from /usr/local/opt/curl/lib/libcurl.4.dylib
(gdb) bt
#0  0x000000010000eb51 in Curl_http_done () from /usr/local/opt/curl/lib/libcurl.4.dylib
#1  0x000000010001fec0 in Curl_done () from /usr/local/opt/curl/lib/libcurl.4.dylib
#2  0x000000010002fbc0 in multi_runsingle () from /usr/local/opt/curl/lib/libcurl.4.dylib
#3  0x000000010002f589 in curl_multi_perform () from /usr/local/opt/curl/lib/libcurl.4.dylib
#4  0x00000001000016d4 in main ()
```

On Ubuntu I get more info, presumably because I compiled with debug symbols and flags:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b444bb in Curl_http_done (conn=0x65f048, status=CURLE_OK, premature=false) at http.c:1483
1483	      free(http->push_headers[http->push_headers_used - 1]);
(gdb) bt
#0  0x00007ffff7b444bb in Curl_http_done (conn=0x65f048, status=CURLE_OK, premature=false) at http.c:1483
#1  0x00007ffff7b621f7 in Curl_done (connp=0x655c38, status=CURLE_OK, premature=false) at url.c:6059
#2  0x00007ffff7b7a636 in multi_runsingle (multi=0x620478, now=..., data=0x655c28) at multi.c:1654
#3  0x00007ffff7b7aad4 in curl_multi_perform (multi_handle=0x620478, running_handles=0x7fffffffe3bc) at multi.c:1808
#4  0x00000000004014e1 in main ()
```

You can see the entire (OS X) output [here](https://gist.github.com/dshafik/ed98035e6cceed8abfe8#file-curl-push-deny-log)

And for `CURL_PUSH_OK` this is the assertion failure on OS X:

```
Assertion failed: (conn->data == data_s), function on_frame_recv, file http2.c, line 411.

Program received signal SIGABRT, Aborted.
0x00007fff8d188286 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
(gdb) bt
#0  0x00007fff8d188286 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff9440c9f9 in pthread_kill () from /usr/lib/system/libsystem_pthread.dylib
#2  0x00007fff8f1389b3 in abort () from /usr/lib/system/libsystem_c.dylib
#3  0x00007fff8f100a99 in __assert_rtn () from /usr/lib/system/libsystem_c.dylib
#4  0x000000010004962e in on_frame_recv () from /usr/local/opt/curl/lib/libcurl.4.dylib
#5  0x000000010007a6f0 in nghttp2_session_on_data_received () from /usr/local/lib/libnghttp2.14.dylib
#6  0x000000010007be59 in nghttp2_session_mem_recv () from /usr/local/lib/libnghttp2.14.dylib
#7  0x000000010004a406 in http2_recv () from /usr/local/opt/curl/lib/libcurl.4.dylib
#8  0x000000010001272a in Curl_read () from /usr/local/opt/curl/lib/libcurl.4.dylib
#9  0x0000000100026bd7 in Curl_readwrite () from /usr/local/opt/curl/lib/libcurl.4.dylib
#10 0x000000010002fd49 in multi_runsingle () from /usr/local/opt/curl/lib/libcurl.4.dylib
#11 0x000000010002f589 in curl_multi_perform () from /usr/local/opt/curl/lib/libcurl.4.dylib
#12 0x0000000100001724 in main ()
```

and on Ubuntu:

```
push: http2.c:411: on_frame_recv: Assertion `conn->data == data_s' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7797267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7797267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff7798eca in __GI_abort () at abort.c:89
#2  0x00007ffff779003d in __assert_fail_base (fmt=0x7ffff78f2028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff7bb5eca "conn->data == data_s", file=file@entry=0x7ffff7bb5d5e "http2.c",
    line=line@entry=411, function=function@entry=0x7ffff7bb6908 <__PRETTY_FUNCTION__.21189> "on_frame_recv") at assert.c:92
#3  0x00007ffff77900f2 in __GI___assert_fail (assertion=0x7ffff7bb5eca "conn->data == data_s", file=0x7ffff7bb5d5e "http2.c", line=411, function=0x7ffff7bb6908 <__PRETTY_FUNCTION__.21189> "on_frame_recv") at assert.c:101
#4  0x00007ffff7b9e44f in on_frame_recv (session=0x791f90, frame=0x792128, userp=0x65f048) at http2.c:411
#5  0x00007ffff7545b1c in session_call_on_frame_received (session=0x791f90, frame=0x792128) at nghttp2_session.c:2980
#6  0x00007ffff754858d in nghttp2_session_on_data_received (session=0x791f90, frame=0x792128) at nghttp2_session.c:4434
#7  0x00007ffff7548623 in session_process_data_frame (session=0x791f90) at nghttp2_session.c:4454
#8  0x00007ffff754ada0 in nghttp2_session_mem_recv (session=0x791f90, in=0x789fa5 "", inlen=45) at nghttp2_session.c:5862
#9  0x00007ffff7b9fd07 in http2_recv (conn=0x65f048, sockindex=0, mem=0x796bb0 "", len=16384, err=0x7fffffffe090) at http2.c:1126
#10 0x00007ffff7b4ac12 in Curl_read (conn=0x65f048, sockfd=6, buf=0x796bb0 "", sizerequested=16384, n=0x7fffffffe118) at sendf.c:589
#11 0x00007ffff7b6b578 in readwrite_data (data=0x796278, conn=0x65f048, k=0x7962f0, didwhat=0x7fffffffe194, done=0x7fffffffe213) at transfer.c:424
#12 0x00007ffff7b6c987 in Curl_readwrite (conn=0x65f048, data=0x796278, done=0x7fffffffe213) at transfer.c:1063
#13 0x00007ffff7b7a26d in multi_runsingle (multi=0x620478, now=..., data=0x796278) at multi.c:1531
#14 0x00007ffff7b7aad4 in curl_multi_perform (multi_handle=0x620478, running_handles=0x7fffffffe3bc) at multi.c:1808
#15 0x00000000004014e1 in main ()
```

With the entire (OS X) output [here](https://gist.github.com/dshafik/ed98035e6cceed8abfe8#file-curl-push-ok-log)

I am able to make this request successfully using `nghttp`, as shown [here](https://gist.github.com/dshafik/ed98035e6cceed8abfe8#file-nghttp-log)

You can easily run the same node.js based server if you have node 5.0.0 (required for ALPN) by cloning [this repo](https://github.com/dshafik/php-http2-push-example) then `cd node-server && npm install && node index.js` which will put it at `localhost:8080`. The server will respond to any request with the same small HTML document, and if supported, try to push `main.js` to the client. (Note: it doesn't respect `SETTINGS_ENABLE_PUSH=0` in the `SETTINGS` frame, which is a protocol error, but doesn't affect this as we are testing with push enabled)

**Comment by bagder** [comment]
commit b4c39010b5 fixes the segfault for me. A case of double-free (clearly due to a lack of test cases for server push). Let me know how it works for you!

**Comment by dshafik** [comment]
This does indeed fix the segfault, and it looks like 419d410ca0728ae591af9f58ef2c1f4132b0a21d fixes the asserts. Is there any way to get this to work with the 7.45.0 release?

**Comment by bagder** [comment]
Not other than applying those patches on the code and rebuild a patched version. Or you just build and use what's in git master right now. The pending curl 7.46.0 release (with these two fixes included) is just two weeks away...

**Comment by dshafik** [comment]
Thanks, I'll bump the requirement to 7.46.0 for support then

**Comment by bagder** [comment]
Thanks for confirming the fix, closing this.
